[package]
name = "rust_ssh_sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
ssh2 = "0.9.4"
library = { path = "./library" }

[workspace]
members = ["library"]